```{r setup}
#install.packages("reticulate")

library(reticulate)
virtualenv_create("fmri-proj")
py_install("seaborn", envname = "fmri-proj")
use_virtualenv("fmri-proj")

```

```{r}
library(reticulate)

py_install("numba")
py_install("jit")
py_install("joblib")
py_install("pandas")
py_install("requests")
py_install("rpy2")

#py_install("cuda")
py_config()
```

```{python setup}
import numpy as np
import torch
import torch.nn as nn
import rpy2
from rpy2 import robjects
from numba import jit, cuda
```

```{python}
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(torch.cuda.is_available())
```

```{r}
# Usa el entorno virtual correcto
use_virtualenv("fmri-proj")

# Ejecuta el código Python para instalar la versión específica de numpy
py_run_string("
import subprocess
subprocess.check_call(['pip', 'install', 'numpy==2.0.2'])
")
```

```{python}

meta_data = r.metadata_MGYS00005592
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(torch.cuda.is_available())

```

```{python}
# Ejecutar código R
robjects.r('''
process_metadata <- function(){
mae <- getResult(mgclnt, meta_dataframe$analysis_accession, usecache = TRUE)
}
''')
```
